In [3]:
!pip install numpy

  Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl (12.8 MB)


In [7]:
import numpy as np

In [8]:
x=np.array([1,2,3,4,5])
print("Array 1-D",x)

Array 1-D [1 2 3 4 5]


In [9]:
#With Numpy
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=a*b
print(c)

#Without Numpy
a=[1,2,3,4]
b=[5,6,7,8]
c=[]
for i in range(len(a)):
    c.append(a[i]*b[i])
print(c)    

[ 5 12 21 32]
[5, 12, 21, 32]


In [10]:
a=np.array([1,2,3,4])
print("Array 1D",a)

b=np.array([[1,2],[3,4]])
print("Array 2D\n",b)

Array 1D [1 2 3 4]
Array 2D
 [[1 2]
 [3 4]]


In [12]:
o=np.ones((3,6))
print("ones \n",o)

z=np.zeros((10,10))
print("Zeros \n",z)

i=np.eye(8)
print("Identical coordinates: \n",i)

r=np.arange(0,11,2)
print("Array: ",r)

seperate=np.linspace(0,1,5)
print("linspace: ",seperate)

ones 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Zeros 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Identical coordinates: 
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
Array:  [ 0  2  4  6  8 10]
linspace:  [0.   0.25 0.5  0.75 1.  ]


In [18]:
'''Operations on arrays using numpy'''
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print("Addition:",a+b)
print("product:",a*b)
print("Square: ",a**2)
print("Sin values: ",np.sin(b))
print("Mean: ",np.mean(a))
print("Max : ",np.max(a))

Addition: [ 6  8 10 12]
product: [ 5 12 21 32]
Square:  [ 1  4  9 16]
Sin values:  [-0.95892427 -0.2794155   0.6569866   0.98935825]
Mean:  2.5
Max :  4


In [21]:
a=np.arange(1,10)
print(a)

reshaped=a.reshape((3,3))
print(reshaped)
linear=reshaped.reshape(-1)
print(linear)

print("greater than 5: ",linear[linear>5])
print("less than 5:",linear[linear<5])

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
greater than 5:  [6 7 8 9]
less than 5: [1 2 3 4]


In [23]:
print("Random numbers between 0 to 3: ",np.random.rand(3))
print("random integer: \n",np.random.randint(1,100),2)

Random numbers between 0 to 3:  [0.13901248 0.60117863 0.87522693]
random integer: 
 60 2


In [26]:
''' code to print a 3x3 matrix which ere filled with boolean value True using numpy'''
import numpy as np
matrix=np.full((3,3),True,dtype=bool)
print(matrix)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
